Attribute VB_Name = "treasury_price_converter"
'Autogenerated code by xlwings - changes will be lost with next import!
#Const App = "Microsoft Excel" 'Adjust when using outside of Excel
Function treasury_price_converter(price)
Attribute treasury_price_converter.VB_Description = "\n    Convert fractional price to decimal price.\n    "
Attribute treasury_price_converter.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        treasury_price_converter = Py.CallUDF("main", "treasury_price_converter", Array(price), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        treasury_price_converter = Py.CallUDF("main", "treasury_price_converter", Array(price))
        Exit Function
    #End If
failed:
    treasury_price_converter = Err.Description
End Function

